/* Copyright 2015 Samsung Electronics Co., LTD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.gearvrf;


/** Wrapper for a GL texture. */
public class GVRTexture extends GVRRecyclableObject {
    protected GVRTexture(GVRContext gvrContext, long ptr) {
        super(gvrContext, ptr);
        gvrContext.getRecyclableObjectProtector().addRecyclableObject(this);
    }

    static GVRTexture factory(GVRContext gvrContext, long ptr) {
        GVRHybridObject wrapper = wrapper(ptr);
        return wrapper == null ? new GVRTexture(gvrContext, ptr)
                : (GVRTexture) wrapper;
    }

    @Override
    protected final boolean registerWrapper() {
        return true;
    }

    /**
     * Get the ID generated by {@code glGenTextures()}.
     * 
     * @return The GL ID of the texture.
     */
    public int getId() {
        return NativeTexture.getId(getPtr());
    }
}

class NativeTexture {
    public static native int getId(long texture);
}
