/*
 * Copyright 2016 Samsung Electronics Co., LTD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gearvrf.io.cursor3d;

/**
 * Register a {@link CursorEventListener} with the {@link CursorManager} to receive
 * events from the cursor.
 * <p/>
 * Look at {@link CursorEvent} to know more about the kind of events generated by the
 * Cursor.
 */
public interface CursorEventListener {

    /**
     * This method is called whenever the state of the {@link Cursor} changes.
     * <p/>
     * For eg. selection/intersection with an object, button clicks and so on.
     *
     * @param event the {@link CursorEvent} to be returned to the application.
     */
    void onEvent(CursorEvent event);
}