package org.gearvrf.io;

import android.view.MotionEvent;

import org.gearvrf.GVRActivity;
import org.gearvrf.GVRContext;
import org.gearvrf.IEvents;

/**
 * This interface describes {@link IEvents} generated from the touchpad of a connected  Android
 * Wear watch. To listen to these  events add a listener to the {@link GVRContext} by calling
 * {@link GVRContext#getEventReceiver()}. These events will only be generated if
 * useAndroidWearTouchpad="true" is used in gvr.xml file. If connected to an Android Wear Watch
 * all the {@link MotionEvent}s generated by interacting with the touchpad of the watch are
 * delivered to the {@link GVRActivity}. The touchpad of the watch can be used as a drop-in
 * replacement for the touchpad on the side of the GearVR headset. it is required that the
 * WearTouchPad app is installed on a phone which is paired to an Android wear watch.
 */
public interface IWearTouchpadEvents extends IEvents {
    /**
     * This is called every time there is a new {@link MotionEvent} from the Andoid wear app.
     * {@link MotionEvent}s are generated every time the user interracts with the touchpad on
     * the Android wear app
     *
     * @param motionEvent
     */
    void onTouchEvent(MotionEvent motionEvent);

    /**
     * This event is generated when a connection to the Android Wear watch is successfully
     * established
     */
    void onConnectionSuccessful();

    /**
     * This event is generated if a connection could not be established to the WearTouchpad app
     * on the Android wear watch. This may be due to the following reasons:
     * 1. WearTouchPad app is not installed on the phone, watch or both.
     * 2. Phone is not connected to a watch.
     */
    void onConnectionFailed();
}