/* Copyright 2015 Samsung Electronics Co., LTD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gearvrf.shaders;

import org.gearvrf.GVRShaderTemplate;

/**
 * Shader used in conjunction with the Beast renderer to render
 * meshes lit by lightmaps generated by Beast.
 * This shader ignores light sources.
 *
 * @<code>
 *     a_position           position vertex attribute
 *     a_texcoord           normal vertex attribute
 *     u_mvp                model/view/projection matrix
 *     lightmap_offset      texture coordinate offset for lightmap
 *     lightmap_scale       texture coordinate scale for lightmap
 *     u_main_texture       texture with diffuse albedo
 *     u_lightmap_texture   texture with lighting
 * </code>
 */
public class GVRLightmapShader extends GVRShaderTemplate
{
    private String vertexShader =
        "#extension GL_ARB_separate_shader_objects : enable\n" +
        "#extension GL_ARB_shading_language_420pack : enable\n" +
        "layout ( location = 0 ) in vec3 a_position;\n" +
        "layout ( location = 1 ) in vec2 a_texcoord;\n" +
        "@MATRIX_UNIFORMS\n" +
        "layout ( location = 0 ) out vec2 diffuse_coord;\n" +
        "void main() {\n" +
        " vec4 pos = u_mvp * vec4(a_position, 1.0);\n" +
        " diffuse_coord = a_texcoord;\n" +
        " gl_Position = pos;\n" +
        "}";

    private String fragmentShader =
        "#extension GL_ARB_separate_shader_objects : enable\n" +
        "#extension GL_ARB_shading_language_420pack : enable\n" +
        "layout ( location = 0 ) in vec2 diffuse_coord;\n" +
        "layout ( set = 0, binding = 2 ) uniform sampler2D u_main_texture;\n" +
        "layout ( set = 0, binding = 3 ) uniform sampler2D u_lightmap_texture;\n" +
        "layout ( set = 0, binding = 0 ) uniform vec2  u_lightmap_offset;\n" +
        "layout ( set = 0, binding = 1 ) uniform vec2  u_lightmap_scale;\n" +
        "layout ( location = 0 ) out vec4 outColor;\n" +
        "void main() {\n" +
        " vec4 color;\n" +
        " vec4 lightmap_color;\n" +
        " vec2 lightmap_coord = (diffuse_coord * u_lightmap_scale) + u_lightmap_offset;\n" +
        // Beast exports the texture with vertical flip
        " lightmap_color = texture(u_lightmap_texture, vec2(lightmap_coord.x, 1.0 - lightmap_coord.y));\n" +
        " color = texture(u_main_texture, diffuse_coord);\n" +
        " outColor = color * lightmap_color;\n" +
        "}";

    public GVRLightmapShader()
    {
        super("float2 u_lightmap_offset float2 u_lightmap_scale",
              "sampler2D u_main_texture, sampler2D u_lightmap_texture",
              "float3 a_position float2 a_texcoord", GLSLESVersion.VULKAN);
        setSegment("FragmentTemplate", fragmentShader);
        setSegment("VertexTemplate", vertexShader);
    }
}