/* Copyright 2015 Samsung Electronics Co., LTD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gearvrf.mixedreality;

/**
 * This interface defines events generated by {@link GVRPlane}
 */
public interface IPlaneEventsListener {
    /**
     * Called when a new plane is detected.
     *
     * @param plane
     */
    void onPlaneDetection(GVRPlane plane);

    /**
     * Called when the tracking state of the plane changes.
     *
     * @param plane
     * @param trackingState
     */
    void onPlaneStateChange(GVRPlane plane, GVRTrackingState trackingState);

    /**
     * Called when the childPlane merges with the parentPlane.
     *
     * @param childPlane
     * @param parentPlane
     */
    void onPlaneMerging(GVRPlane childPlane, GVRPlane parentPlane);
}
