/* Copyright 2016 Samsung Electronics Co., LTD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gearvrf;

/**
 * This interface defines events generated by picking.
 * @see GVRPicker
 * @see GVRPicker.GVRPickedObject
 */
public interface IPickEvents extends IEvents {
    /**
     * Called when the set of objects picked changes.
     * @param picker GVRPicker which generated the event.
     */
    void onPick(GVRPicker picker);
    
    /**
     * Called when the set of objects picked is empty.
     * @param picker GVRPicker which generated the event.
     */    
    void onNoPick(GVRPicker picker);
    
    /**
     * Called when the pick ray first enters a scene object.
     * @param sceneObj scene object picked
     * @param collision information about the collision
     */
    void onEnter(GVRSceneObject sceneObj, GVRPicker.GVRPickedObject collision);
    
    /**
     * Called when the pick ray first exits a scene object.
     * @param sceneObj scene object no longer picked.
     */    
    void onExit(GVRSceneObject sceneObj);
    
    /**
     * Called while the pick ray penetrates a scene object.
     * @param sceneObj scene object picked
     * @param collision information about the collision
     */    
    void onInside(GVRSceneObject sceneObj, GVRPicker.GVRPickedObject collision);
}
