package org.gearvrf;

/**
 * Interface for a renderable entity.
 *
 * Something is renderable if it has an attached mesh and material.
 */
public interface IRenderable
{
    /**
     * Get the GVRMaterial associated with this renderable entity.
     * @return GVRMaterial
     */
    public GVRMaterial  getMaterial();

    /**
     * Get the GVRMesh associated with this renderable entity.
     * @return GVRMesh
     */
    public GVRMesh      getMesh();

    /**
     * Determine if this renderable uses light sources.
     */
    public boolean      isLightEnabled();

    /**
     * Save the native Shader ID for this renderable.
     * @param shaderID integer representing a native shader ID generated by GVRShader#bindShader
     */
    public void         setShader(int shaderID, boolean isMultiview);

    public GVRContext getGVRContext();
}
